{% set name = "georaster" %}
{% set version = "1.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 167e23d8e5bddb86816c6b24dc2f020c99af8a2c0a56df9e135a4485409c40f2

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - gdal
    - pyproj

test:
  imports:
    - georaster

about:
  home: https://github.com/atedstone/georaster
  license: GNU GPL v.3
  summary: 'easy processing and analysis of geographic and projected rasters'
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  doc_url: http://georaster.readthedocs.io
  dev_url: https://github.com/atedstone/georaster

extra:
  recipe-maintainers:
    - atedstone
