{% set name = "georaster" %}
{% set version = "v1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/GeoUtils/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4c3263954b70cdf399cb1c35b9dc54993924d99460814dae71c604bf8aa34e45

build:
    number: 1
    script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - gdal
    - pyproj

test:
  imports:
    - georaster

about:
  home: https://github.com/GeoUtils/georaster
  license: GNU GPL v.3
  summary: 'easy processing and analysis of geographic and projected rasters'
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  doc_url: http://georaster.readthedocs.io
  dev_url: https://github.com/GeoUtils/georaster

extra:
  recipe-maintainers:
    - atedstone
