{% set version = "1.26" %}

package:
  name: georaster
  version: {{ version }}

source:
  url: https://github.com/GeoUtils/georaster/archive/v{{ version }}.tar.gz
  sha256: 4c3263954b70cdf399cb1c35b9dc54993924d99460814dae71c604bf8aa34e45

build:
    number: 1
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python

  run:
    - python
    - numpy
    - scipy
    - gdal
    - pyproj

test:
  imports:
    - georaster

about:
  home: https://github.com/GeoUtils/georaster
  license: GPL-3.0
  summary: 'Easy processing and analysis of geographic and projected rasters'
  license_family: GPL3
  license_file: LICENSE.txt
  doc_url: http://georaster.readthedocs.io
  dev_url: https://github.com/GeoUtils/georaster

extra:
  recipe-maintainers:
    - atedstone
