travis:
  secure:
    BINSTAR_TOKEN: T1UH/CeZMh4qT/kZ1yL5nYrHeI9CtgPXjOY/a9mzdVkw1Yjyz36F/fg8v2b+JcW0uh+ptA6ZWVzVeir2WjtXwEfW/ksjVD/8wgqMo5+uvCy/GilCBUb7mTBdfg304NZ0tm5MYPpPZmwBn7P2IEPO8fVSvWy4/yNy4nnuIAWKAtRzWx17qsa10MVtSlW7/7QKwZvISESeeLdyCYKLYLYMB9gG2GxWI7wi3tBf4r/TLJc50JvZZT11+RYTJ8ErUw+s/epxf1ltAFAPitp/bQxm8N1fVAb/iWtvq6+lQk7UCNkmlDBKtTkHqbdJYZjEkM/H4k4r01sCNBZAe6iY5c9RRoOO7SLAFan+6wduI7kmlMiS5BEfrkX8NcZkxfZyWNd56twrpb1g59nC2uuo4UuQwLGDQ0ax5c5JnBYkLMIj0yj4/3ulsC/+AMgz+38sUrhZIFVl3a/lbNskHeSOea8FFLAweKcg9J0x9HCqnQJQeGPDUjv5NWup2URku/2jNkxAUFXr0dMZ5Mk8d5QZz9rJ3jEiO8MeK5RZE7uCkTAhGLcplyNCzu369NlAf8YBT9oZ+wTDTPctcSqcxnjmyS2wXSww8MjpJ59pvttvBfiEDx2JtLiz4ro4S9URKGQbgHD/UzwtqWIoSMuRGYeAhvde7PRon/xRLhW/aFbBxDPW08A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
