travis:
  secure:
    BINSTAR_TOKEN: gcg9TTtKtB+i9q2zHn+G8IM80bgiq7UXNimopCDQM2z8ELCPHBmVPxk4AMdNqg8pTHoicV/vzi/W5xS0Z7jf+aYHx83jFzbCl4MX/OHKbqSZBaIamIBKRHZxEcFA8UV5QyaxYb6NxXFdh518gqP2GwKDZ+WSiWMaTdZc9Eb8wAhquwSlC8rsJgczHeeo5/AupcKJCugVnpRiz7Vh3nQuod4SVlnw7DPrB0Zn+jcr6sA9byse17M0OOi/MNPbCdzA5/4sukd0AuES322fmuUeYBwILZXNgfz0Z9Zqx6fkIYJKFY39Y56eJM6syx47idI4VFsPygeJS9mO7Cbz2NtmECjudF3Qa4mOYcRmGnU0HZBH6MVmj2Pm/Djq1UGFz/03PlXhoMKWJA0H1oakI+3rWWi7mogIBTZL532QJBts86hRgnp3488mige/UTnGZO13oussi+9bU2P3UNaD2StPvMli2AMsJSd2Yi8QEKRw6jjPJTpj2bteCM42UlCOrN1ZNTvBzMycQI+LtNCq+bRicA+ufxK7O2NP91Lcw/UemZoWlhHiqeLmg9ZsPD9aAe5vIEwmk/cZrcP6ygYoAJo/ZWjkPCKdWRGKINiOxq71pskvpw9/p2LJzPcjfiGjKUhi5WbCcZuk3dvdqwFPy4xdQAxgDON4VEtWnkSPsvlyt14=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
