travis:
  secure:
    BINSTAR_TOKEN: g/BxSMV7yVTRCbFQbADnC8rEE/Tz6w7tl37PRN9CcnPtL/nkZFlCr0qoyYmH6ViS247UQT5TkDPXyvTzqXLT13O9bY+Q7obJhgfySevLdAd9JvBF00eC5Bw0mUbOjwnD4pqcb4/NUNZZ85g4FrOGDg17HS/hPGnm21GFoB2fWI5lNhqgq1tgKsW0iXtfWCD267gQT4e+TLRRVG7/VagjtyLCan4vzSriSz3fImJaqxgdaid7oLHqo+lpxf8GwRheyDMhXt0pd+o1GBm+c/SGi9eFAifM6vXsSU4jzJIfvpi1dfIbVDuXxizqOoZXlg2Ry1XkPkb97OsNV5CeI0eSgxJAsyLIuy9Y/ay4a/tblTvwDM3lgO4eNhXTtG0mbJmeElmpeLIIgsbWGjWzeMi0jRYIQOEC+AhGUjUDpOBhHfgC2kR8feRK07WPMnygBuwL82KDEwGtM/GCQDt5txw7TPSHoDxRtDrAoXLCtSkTkSigUKNiDvy+KGaZ/16icng/J5OMCGQHdwaDect4TGuPxuCxWBfsJXv8IHMnLxYvbHGsYBWbSN5mOEGZt87nO3mLjkARKTyPDwGmEwtoonN4Gyvy0/mHBdqXl0bc+ll/rTMVDcCfFWVjL0LNbh4lSsfglvktYECXk3PS3+iDO76b8Nw49tgclBwxqmuvicWMGmY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
